name: Crystal CI

on:
  push:
  schedule:
    - cron: "0 2 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal:latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Run Lint
      run: |
        bin/ameba
        crystal tool format --check

